import { Artist } from '@/types/artwork';

// This data is structured to be compatible with both the frontend Artist type
// and the digital_artist_data.py structure
export const digitalArtist: Artist = {
  // ID is generated by the backend when the artist is created
  // This is stored internally for database references but not displayed in the UI
  // The frontend should never allow users to edit this field
  id: "8f7e6d5c-4b3a-2a1b-0c9d-8e7f6a5b4c3d", // UUID format as typically used by backends
  name: "Elena Vasquez",
  age: 32,
  location: "Mexico City, Mexico",
  email: "elena@vasquezart.com",
  bio: "Digital abstract painter using Procreate & Photoshop. 5+ years experience.",
  website: "vasquezart.com",
  profileImage: "/artists/artist1.jpg", // Using a placeholder image
  experience: "5+ years",
  primaryMedium: "Digital Art, Procreate, Photoshop",
  skills: "Digital painting, Abstract art, NFT creation, Mural design",
  
  // Format compatible with the frontend
  socialLinks: {
    instagram: "@elenavasquez_art",
    twitter: "vasquezart",
    website: "https://vasquezart.com"
  },
  
  // Format compatible with digital_artist_data.py
  socialArray: ["@elenavasquez_art (IG)", "twitter.com/vasquezart"],
  
  // Gallery items with the detailed format from digital_artist_data.py
  gallery: [
    {
      id: "IMG001",
      title: "Urban Pulse",
      year: 2024,
      medium: "Digital (Procreate)",
      url: "https://images.unsplash.com/photo-1579783902614-202f9c163d47?w=400",
      description: "Bold red/orange swirls in Procreate. 300 DPI export for mural printing. Exhibited: Zona MACO 2024. Status: Sold as NFT + Print"
    },
    {
      id: "IMG002",
      title: "Silent Storm",
      year: 2023,
      medium: "Digital (Photoshop)",
      url: "https://images.unsplash.com/photo-1549497538-3036590a1a2f?w=400",
      description: "Layered blues with 50+ adjustment layers. NFT drop on Foundation. Status: Sold as NFT"
    },
    {
      id: "IMG003",
      title: "City Dreams",
      year: 2022,
      medium: "Digital (Procreate + Collage)",
      url: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
      description: "Metro ticket scans composited in Photoshop. Airbnb HQ digital wallpaper. Status: Licensed"
    },
    {
      id: "IMG004",
      title: "Echoes",
      year: 2021,
      medium: "Digital Painting (Procreate)",
      url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400",
      description: "Gradient mesh circles. OpenSea NFT collection (1/10 editions). Status: Sold out"
    },
    {
      id: "IMG005",
      title: "Mexico City Mural - Digital Concept",
      year: 2023,
      medium: "Digital Mockup (Photoshop)",
      url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
      description: "20ft mural concept rendered at 8K. Used for city approval. Status: Physical mural completed"
    }
  ]
};
